/* This program will read the Outfile generated by
 * the CoordinateGenerator program, store those files
 * into a vector then output all the values of the vector
 * array.
 */
 
#include <iostream>
#include <fstream>
#include <vector>

using namespace std;

struct Coordinates
{
	//This is the basic data structure for the coordinates from the file.
	int x;
	int y;
};

int main(int argc, char **argv)
{
	//Variable declaration for the file reading.
	int NumberOfCoordinates; int XCoordinate; int YCoordinate;
	
	//File reading declaration.
	ifstream InFile;
	InFile.open(argv[1]);
	
	InFile >> NumberOfCoordinates;
	
	//Vector storage declaration
	vector<Coordinates> CoordinateStorage;
	
	//File reading and storing the variables into the Coordinates data structure.
	for (int n = 0; n < NumberOfCoordinates; n++)
	{
		//The two entries are read and then stored in the temporary variables of x and y.
		InFile >> XCoordinate >> YCoordinate;	
		
		//The data structure is no declared and the x and y are stored in the in the structure.
		Coordinates Coordinate;
		
		Coordinate.x = XCoordinate;
		Coordinate.y = YCoordinate;
		
		CoordinateStorage.push_back(Coordinate);
	
	}
	
	//The vector contents will now be printed to the terminal.
	for (int n = 0; n < NumberOfCoordinates; n++)
	{
		cout << CoordinateStorage[n].x << " " << CoordinateStorage[n].y << "\n";
	}
	
	//End of the file read and program.
	InFile.close();
	
	return 0;
}